@startuml

actor "Usuário" as U

rectangle "Hotelaria" {
    usecase "Filtrar hotéis\n(zona rural / urbana)" as UC1
    usecase "Visualizar cards de hotéis" as UC2
    usecase "Abrir mais detalhes" as UC3
}

U --> UC1
U --> UC2
U --> UC3

@enduml
