@startuml

actor "Usuário" as U

rectangle "Página Inicial" {
    usecase "Visualizar carrossel automático" as UC1
    usecase "Calcular distância\naté São Miguel Arcanjo" as UC2
}

U --> UC1
U --> UC2

@enduml
